Repository implude/meat-in-android, pull requests merged in 2021-09, with the labels that each got.

#12 feat(presentation): implement design system
  app/src/main/java/app/meatin/ui/theme/Color.kt
  app/src/main/java/app/meatin/ui/theme/Theme.kt
  app/src/main/java/app/meatin/ui/theme/Type.kt
  app/src/main/res/font/pretendard_bold.otf
  app/src/main/res/font/pretendard_medium.otf
  app/src/main/res/font/pretendard_regular.otf
  app/src/main/res/font/pretendard_semibold.otf
Labels: Scope: Presentation, Type: Feature, Priority: 🔥🔥

#15 fix(presentation): change typography
  app/src/main/java/app/meatin/ui/theme/Type.kt
Labels: Scope: Presentation, Type: Fix, Priority: 🔥🔥

#11 feat(presentation): add RecipeCard composable
  app/src/main/AndroidManifest.xml
  app/src/main/java/app/meatin/ui/composables/RecipeCard.kt
  app/src/main/java/app/meatin/ui/theme/Type.kt
  app/src/main/res/drawable/ic_heart.xml
Labels: Scope: Presentation, Type: Feature, Priority: 🔥🔥

#16 feat(presentation): add advertisement composable
  app/src/main/java/app/meatin/ui/composables/Advertisement.kt
Labels: Scope: Presentation, Type: Feature, Priority: 🔥🔥

#17 feat(presentation): build post card composable
  app/build.gradle
  app/src/main/java/app/meatin/ui/composables/PostCard.kt
Labels: Scope: Presentation, Type: Feature, Priority: 🔥🔥

#24 fix(presentation): change to new typography system
  app/src/main/java/app/meatin/ui/theme/Type.kt
Labels: Scope: Presentation, Type: Fix, Priority: 🔥🔥

#28 fix: icon size
  app/src/main/java/app/meatin/ui/composables/PostCard.kt
Labels: Scope: Presentation, Type: Fix, Priority: 🔥

#30 feat: add profile button
  app/build.gradle
  app/src/main/java/app/meatin/ui/composables/ProfileButton.kt
  app/src/main/res/drawable/ic_right_arrow.xml
Labels: Scope: Presentation, Scope: Dependency, Type: Feature, Priority: 🔥🔥

#23 feat(presentation): build comment item
  app/src/main/java/app/meatin/ui/composables/CommentItem.kt
Labels: Scope: Presentation, Type: Feature, Priority: 🔥🔥

#33 feat(presentation): add custom switch component
  app/src/main/java/app/meatin/ui/composables/components/MeatInSwitch.kt
Labels: Scope: Presentation, Type: Feature, Priority: 🔥
