Repository implude/meat-in-android, pull requests merged in 2021-10, with the labels that each got.

#41 fix(presentation): apply typography
  app/src/main/java/app/meatin/ui/composables/CommentItem.kt
  app/src/main/java/app/meatin/ui/composables/ProfileButton.kt
Labels: Scope: Presentation, Type: Fix, Priority: 🔥🔥🔥

#47 refactor: change CoreText.kt package to composefix
  app/src/main/java/app/meatin/ui/composables/Advertisement.kt
  app/src/main/java/app/meatin/ui/composables/CommentItem.kt
  app/src/main/java/app/meatin/ui/composables/PostCard.kt
  app/src/main/java/app/meatin/ui/composables/ProfileButton.kt
  app/src/main/java/app/meatin/ui/composables/RecipeBriefItem.kt
  app/src/main/java/app/meatin/ui/composables/RecipeCard.kt
  app/src/main/java/app/meatin/ui/theme/composefix/CoreText.kt
Labels: Priority: 🔥, Type: Chore

#48 chore(deps): add retrofit2 library
  app/build.gradle
Labels: Scope: Dependency, Priority: 🔥🔥, Type: Chore

#54 fix(presentation): ellipt profile button text
  app/src/main/java/app/meatin/ui/composables/ProfileButton.kt
Labels: Scope: Presentation, Type: Fix, Priority: 🔥

#57 refactor(presentation): move all component files to components package
  app/src/main/java/app/meatin/ui/composables/components/Advertisement.kt
  app/src/main/java/app/meatin/ui/composables/components/CommentItem.kt
  app/src/main/java/app/meatin/ui/composables/components/PostCard.kt
  app/src/main/java/app/meatin/ui/composables/components/ProfileButton.kt
  app/src/main/java/app/meatin/ui/composables/components/RecipeBriefItem.kt
  app/src/main/java/app/meatin/ui/composables/components/RecipeCard.kt
  app/src/main/java/app/meatin/ui/composables/components/TaggedRecipe.kt
Labels: Scope: Presentation, Type: Refactor, Priority: 🔥🔥

#31 feat(presentation): add ingredient item composable
  app/src/main/java/app/meatin/ui/composables/IngredientItem.kt
Labels: Scope: Presentation, Type: Feature, Priority: 🔥🔥

#62 fix(domain): switch `BreifCommunityUser` and `CommunityUser`
  app/src/main/java/app/meatin/domain/model/BriefCommunityUser.kt
  app/src/main/java/app/meatin/domain/model/CommunityUser.kt
Labels: Scope: Domain, Priority: 🔥🔥🔥, Resolution: Fixed
