Repository implude/meat-in-android, pull requests merged in 2021-11, with the labels that each got.

#74 feat(presentation): add meat type navigation
  app/src/main/java/app/meatin/ui/composables/components/MeatTypeNavigation.kt
Labels: Scope: Presentation, Type: Feature, Priority: 🔥🔥

#72 refactor: move `TitledLabel` to components
  app/src/main/java/app/meatin/ui/composables/components/TitledLabel.kt
Labels: Scope: Presentation, Type: Refactor, Priority: 🔥

#77 feat: add clickable
  app/src/main/java/app/meatin/ui/composables/components/TaggedRecipe.kt
Labels: Scope: Presentation, Type: Feature, Priority: 🔥🔥🔥
