Repository implude/meat-in-android, pull requests merged in 2021-12, with the labels that each got.

#79 fix(presentation): keep `PostCard` from cutting off
  app/src/main/java/app/meatin/domain/model/BriefPost.kt
  app/src/main/java/app/meatin/domain/model/FakeValues.kt
  app/src/main/java/app/meatin/ui/composables/components/PostCard.kt
  app/src/main/java/app/meatin/ui/composables/components/PostPreviewCard.kt
  app/src/main/res/drawable/ic_comment.xml
Labels: Scope: Presentation, Type: Fix, Priority: 🔥🔥🔥

#71 feat(presentation): add timer
  app/src/main/java/app/meatin/ui/composables/components/Timer.kt
Labels: Scope: Presentation, Type: Feature, Priority: 🔥

#81 feat(presentation): add `LoginScreen` composable
  app/src/main/java/app/meatin/ui/composables/LoginScreen.kt
Labels: Scope: Presentation, Type: Feature, Priority: 🔥🔥

#83 feat(presentation): build main screen
  app/src/main/java/app/meatin/domain/model/AdvertisementModel.kt
  app/src/main/java/app/meatin/domain/model/FakeValues.kt
  app/src/main/java/app/meatin/ui/composables/MainScreen.kt
  app/src/main/res/drawable/ic_fire.xml
  app/src/main/res/drawable/ic_logo.xml
Labels: Scope: Presentation, Type: Feature, Priority: 🔥🔥

#76 feat(presentation): add recipe overview screen
  app/src/main/AndroidManifest.xml
  app/src/main/java/app/meatin/domain/model/BriefPost.kt
  app/src/main/java/app/meatin/domain/model/FakeValues.kt
  app/src/main/java/app/meatin/ui/composables/RecipeOverviewScreen.kt
  app/src/main/java/app/meatin/ui/composables/components/IngredientItem.kt
  app/src/main/res/drawable/ic_cook.xml
Labels: Scope: Presentation, Type: Feature, Priority: 🔥🔥

#66 feat(presentation): build post detail screen
  app/src/main/java/app/meatin/ui/composables/PostDetailScreen.kt
  app/src/main/java/app/meatin/ui/composables/components/TaggedRecipe.kt
Labels: Scope: Presentation, Type: Feature, Priority: 🔥🔥

#82 Feat/chip
  app/src/main/java/app/meatin/ui/composables/components/Chip.kt
Labels: Scope: Presentation, Type: Feature, Priority: 🔥🔥

#87 fix: delete chip and chip group padding
  app/src/main/java/app/meatin/ui/composables/components/Chip.kt
Labels: Scope: Presentation, Type: Fix, Priority: 🔥🔥🔥

#89 feat(presentation): build barocook fin
  app/src/main/java/app/meatin/ui/composables/BaroCookFin.kt
  app/src/main/res/drawable/ic_right_arrow2.xml
Labels: Scope: Presentation, Type: Feature, Priority: 🔥🔥

#88 feat(presentation): add splash screen
  app/src/main/java/app/meatin/ui/MainActivity.kt
  app/src/main/java/app/meatin/ui/composables/LoginScreen.kt
  app/src/main/java/app/meatin/ui/composables/SplashScreen.kt
  app/src/main/java/app/meatin/ui/viewmodel/AuthViewModel.kt
  app/src/main/java/app/meatin/util/SingleLiveEvent.kt
Labels: Scope: Presentation, Type: Feature, Priority: 🔥

#91 feat(presentation): add barocook screen
  app/src/main/java/app/meatin/ui/composables/BaroCookScreen.kt
Labels: Scope: Presentation, Type: Feature, Priority: 🔥🔥🔥

#92 Privacy policy
  app/src/main/java/app/meatin/ui/composables/RegisterScreen.kt
Labels: Scope: Presentation, Type: Feature, Priority: 🔥🔥🔥

#93 feat(presentation): add recipe view
  app/src/main/AndroidManifest.xml
  app/src/main/java/app/meatin/data/repositories/RecipeRepositoryImpl.kt
  app/src/main/java/app/meatin/domain/model/BriefRecipe.kt
  app/src/main/java/app/meatin/domain/model/Recipe.kt
  app/src/main/java/app/meatin/domain/model/RecipeStep.kt
  app/src/main/java/app/meatin/domain/repositories/RecipeRepository.kt
  app/src/main/java/app/meatin/domain/services/MeatInService.kt
  app/src/main/java/app/meatin/ui/MainActivity.kt
  app/src/main/java/app/meatin/ui/composables/InnerRecipeStepScreen.kt
  app/src/main/java/app/meatin/ui/composables/MainScreen.kt
  app/src/main/java/app/meatin/ui/composables/PostDetailScreen.kt
  app/src/main/java/app/meatin/ui/composables/RecipeCookFin.kt
  app/src/main/java/app/meatin/ui/composables/RecipeStepsScreen.kt
  app/src/main/java/app/meatin/ui/composables/components/RecipeCard.kt
  app/src/main/java/app/meatin/ui/composables/components/TaggedRecipe.kt
  app/src/main/java/app/meatin/ui/theme/Theme.kt
  app/src/main/java/app/meatin/ui/viewmodel/MainViewModel.kt
  app/src/main/java/app/meatin/ui/viewmodel/PostViewModel.kt
  app/src/main/java/app/meatin/ui/viewmodel/RecipeViewModel.kt
  app/src/main/res/drawable/meatin_app_logo.png
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
Labels: Scope: Presentation, Type: Feature, Priority: 🔥🔥🔥

#90 Barocook timer setup screen
  app/src/main/java/app/meatin/ui/composables/BarocookTimerSetupScreen.kt
Labels: Scope: Presentation, Type: Feature, Priority: 🔥🔥

#95 feat(presentation): add barocook
  app/src/main/java/app/meatin/domain/model/RecipeDisplayable.kt
  app/src/main/java/app/meatin/domain/model/RecipeStep.kt
  app/src/main/java/app/meatin/ui/MainActivity.kt
  app/src/main/java/app/meatin/ui/composables/BaroCookFin.kt
  app/src/main/java/app/meatin/ui/composables/BaroCookScreen.kt
  app/src/main/java/app/meatin/ui/composables/InnerRecipeStepScreen.kt
  app/src/main/java/app/meatin/ui/composables/MainScreen.kt
  app/src/main/java/app/meatin/ui/composables/RecipeCookFin.kt
  app/src/main/java/app/meatin/ui/composables/RecipeStepsScreen.kt
  app/src/main/java/app/meatin/ui/composables/components/Timer.kt
  app/src/main/java/app/meatin/ui/viewmodel/RecipeViewModel.kt
Labels: Scope: Presentation, Type: Feature, Priority: 🔥🔥🔥

#96 fix: fix emergency bug
  app/src/main/java/app/meatin/domain/model/BriefCommunityUser.kt
  app/src/main/java/app/meatin/ui/composables/PostDetailScreen.kt
  app/src/main/java/app/meatin/ui/composables/RecipeOverviewScreen.kt
  app/src/main/java/app/meatin/ui/composables/components/PostPreviewCard.kt
Labels: Scope: Domain, Type: Fix, Priority: 🔥🔥🔥
